### ISSUE TITLE
Additional dependencies required to run locally?

### ISSUE THREAD

**Issue by simonprickett** [byronrosas/helplanet#1]
Hi @byronrosas,

I was able to clone this project and run it locally but had to install the following globally, which you might want to mention in your README:

* `@ionic/cli` to get the `ionic` command.
* `@angular/cli` to get the `ng` command.

I also found that I needed to install the following extra dependency to make the project start and run: `@ionic-native/core`.  After that, I was able to start the application successfully.

**Comment by byronrosas** [comment]
Hi thanks for letting me know
I already added it to the README file. 
Greetings 
________________________________
De: Simon Prickett ***@***.***>
Enviado: lunes, 24 de mayo de 2021 10:54
Para: byronrosas/helplanet ***@***.***>
Cc: byronrosas ***@***.***>; Mention ***@***.***>
Asunto: [byronrosas/helplanet] Additional dependencies required to run locally? (#1)


Hi @byronrosas<https://github.com/byronrosas>,

I was able to clone this project and run it locally but had to install the following globally, which you might want to mention in your README:

  *   @ionic/cli to get the ionic command.
  *   @angular/cli to get the ng command.

I also found that I needed to install the following extra dependency to make the project start and run: @ionic-native/core. After that, I was able to start the application successfully.
